on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: vjtestregistry.azurecr.io
        username: ${{ secrets.acr_vjtestregistry_username }}
        password: ${{ secrets.acr_vjtestregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t vjtestregistry.azurecr.io/aks:${{ github.sha }}
        docker push vjtestregistry.azurecr.io/aks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vjtestaks | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vjtestaks`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vjtestaks
        container-registry-url: vjtestregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_vjtestregistry_username }}
        container-registry-password: ${{ secrets.acr_vjtestregistry_password }}
        secret-name: aksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: vjtestaks
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          vjtestregistry.azurecr.io/aks:${{ github.sha }}
        imagepullsecrets: |
          aksdockerauth